# Generated by Django 4.2 on 2023-05-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default=1, upload_to='Profile', verbose_name='الصورة الشخصية : '),
            preserve_default=False,
        ),
    ]
