# Generated by Django 4.2 on 2023-05-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_img_alter_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Waiting_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='مده الانتظار'),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='google',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='التقييم'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subtitle',
            field=models.TextField(blank=True, max_length=70, null=True, verbose_name='نبذه عنك'),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='اللقب'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='type_doctors',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=20, verbose_name='النوع'),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عدد ساعات العمل'),
        ),
    ]
