# Generated by Django 4.2 on 2023-05-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_specialist_doctor_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, choices=[('جراحة سمنة ومناظير ', 'جراحة سمنة ومناظير '), ('جراحة أطفال', 'جراحة أطفال'), ('مخ وأعصاب', 'مخ وأعصاب'), ('جلدية', 'جلدية'), ('أورام', 'أورام'), ('أنف وأذن وحنجرة', 'أنف وأذن وحنجرة'), ('أطفال حديثي الولادة', 'أطفال حديثي الولادة'), ('نساء وتوليد', 'نساء وتوليد'), ('جراحة أورام', 'جراحة أورام'), ('جراحة تجميل', 'جراحة تجميل'), ('قلب وأوعيه دموية', 'قلب وأوعيه دموية'), ('تخسيس وتغذية', 'تخسيس وتغذية'), ('باطنة', 'باطنة'), ('جراحة أوعيه دموية', 'جراحة أوعيه دموية'), ('أمراض دم', 'أمراض دم'), ('عظام', 'عظام'), ('نفسي', 'نفسي'), ('أسنان', 'أسنان')], max_length=50, null=True, verbose_name='دكتور ؟'),
        ),
    ]
